### ISSUE TITLE
How does it work? I think it doesn't work and need update, installed and no timestamps in chat on Caali proxy.

### ISSUE THREAD

**Issue by Zezo12345** [Gl0/TeraTimeStamps#1]

**Comment by Gl0** [comment]
Check log, may be some other mod installs gpk with the same name (   S1UI_BaseUI.gpk  ) or some error happens. Also may be you have copy of that gpk somewere in your Tera folder, and it have higher priority than installed by toolbox.

**Comment by Zezo12345** [comment]
I just had owyn fps pack client mod installed and it seems its not compatible with one. Not sure how to make both work together. Got any ideas? It doesn't have to be automatic, i already tried to place your gpk file through a generic gpk loader mod and that didn't work too.

**Comment by Gl0** [comment]
Fpspack shouldn't affect it as far as I see.
Does it work with fpspack disabled?

**Comment by Zezo12345** [comment]
Yes when i removed fps pack it worked.

**Comment by Zezo12345** [comment]
I guess its not your fault that another mod messes up yours, ill close this issue. Hope you can make them sometime later work together. Thank you for your time.
